### PR TITLE
Fix #98

### LINKED ISSUE #98: Service crashes when clients connect without session id

### PR DESCRIPTION
**Pull request by DaQuirm**
Fix #98

### CODE REVIEW

File: app/facets/participant/participant.coffee [hunk 1]
```diff
@@ -12,12 +12,21 @@ class Participant
...
-				game_session.add_participant @
+				game_session?.add_participant @
+
+		@game_session_id = new nx.Cell
+			'->': [
+				((id) =>
+					if @service.game_sessions.has id
+						@game_session
+					else
+						[]
```
Comment (kirilknysh) [inline app/facets/participant/participant.coffee]: Is empty array `[]` correct **default** value for `game_sesstion_id`?

Comment (DaQuirm) [inline app/facets/participant/participant.coffee]: That's not a default value but sync target, that is, if there's a session then the target is `game_session` cell, otherwise there are no sync targets (`undefined` would be better, but currently nexus understands only cells or arrays of cells, hence `[]`)

SO UGLY :crying_cat_face:

Comment (kirilknysh) [inline app/facets/participant/participant.coffee]: ok, now I see... let it be so, at least for now. In future - it would be nice to have some comments in code for such cases

Comment (DaQuirm) [inline app/facets/participant/participant.coffee]: Right.
Additionally, refer to https://github.com/DaQuirm/nexus/wiki/Bindings-and-Cells#demux-binding

**Comment by kirilknysh** [comment]
LGTM
